'use strict';
/* ===== 데이터: 난이도 · 무장 · 적 · 스테이지 · 아이템 ===== */
const DIFFS=[
 {id:'easy',name:'쉬움',desc:'적 체력·공격력 대폭 감소 · 목숨 4개',ehp:.7,edmg:.55,lives:4,aggr:.7,extra:0,drop:1.4,score:.8,col:'#7fd67f'},
 {id:'normal',name:'보통',desc:'원작에 가까운 밸런스 · 목숨 2개',ehp:1,edmg:1,lives:2,aggr:1,extra:0,drop:1,score:1,col:'#ffe08a'},
 {id:'hard',name:'어려움',desc:'적이 강하고 공격적 · 증원 +1 · 목숨 1개',ehp:1.35,edmg:1.45,lives:1,aggr:1.35,extra:1,drop:.8,score:1.5,col:'#ff9a50'},
 {id:'hell',name:'지옥',desc:'한 번 쓰러지면 끝 · 증원 +2 · 점수 2.5배',ehp:1.8,edmg:2.1,lives:0,aggr:1.7,extra:2,drop:.6,score:2.5,col:'#ff4040'}];

const HEROES=[
 {id:'guan',name:'관우',zi:'운장',title:'미염공',weapon:'청룡언월도',spName:'청룡언월참',sp:'crescent',hp:125,pow:14,spd:3.1,reach:100,fx:'#5dffa0',
  look:{skin:'#b8452f',hair:'#15120e',body:'#2f7d3b',sub:'#d4af37',pants:'#233523',boots:'#2a1a10',hat:'guan',hs:'long',eye:'#3a8a4a',beard:'long',weapon:'glaive',armor:'plate',cape:'#1e5a28',face:'fierce'},
  desc:['팔십이 근 청룡언월도를 휘두르는 의리의 무신.','공격 범위가 넓고 한 방이 묵직하다.','필살기: 청룡이 깃든 거대한 초승달 참격.'],
  end:'관우는 청룡도를 거두며 말했다. "형님, 도원의 약조를 지켰소."'},
 {id:'zhang',name:'장비',zi:'익덕',title:'연인',weapon:'장팔사모',spName:'장판대갈',sp:'roar',hp:138,pow:15,spd:2.9,reach:94,fx:'#ff6a3a',
  look:{skin:'#d9a878',hair:'#111111',body:'#3b3b3b',sub:'#b03a2e',pants:'#1f1f1f',boots:'#1a1a1a',hat:'zhang',hs:'spiky',eye:'#b04a20',beard:'spiky',weapon:'snake',armor:'plate',cape:'#5a1a14',face:'fierce'},
  desc:['만인지적(萬人之敵). 최고의 체력과 파괴력.','한 번의 호통으로 적진을 뒤흔든다.','필살기: 대지를 가르는 대갈일성, 화면 전체 타격.'],
  end:'장비는 술잔을 높이 들었다. "하하! 오늘은 천하가 다 내 술안주로구나!"'},
 {id:'zhao',name:'조운',zi:'자룡',title:'상산 조자룡',weapon:'애각창',spName:'백룡돌격',sp:'dash',hp:110,pow:12,spd:4.1,reach:96,fx:'#bfe6ff',
  look:{skin:'#f0c8a0',hair:'#221a14',body:'#e8edf2',sub:'#3a6fc4',pants:'#4a5a7a',boots:'#dfe6ee',hat:'zhao',hs:'short',eye:'#3a7ae0',beard:null,weapon:'spear',armor:'plate',cape:'#2a5aa8',face:'normal'},
  desc:['온몸이 담(膽)덩어리인 상산의 용.','가장 빠른 발과 긴 창으로 적을 꿰뚫는다.','필살기: 백룡의 기운을 두른 무적 돌진.'],
  end:'조운은 창끝을 내리고 백마의 갈기를 쓰다듬었다. "백성들이 무사하니 그것으로 족하다."'},
 {id:'huang',name:'황충',zi:'한승',title:'노익장',weapon:'봉황궁·대도',spName:'만궁난사',sp:'rain',hp:115,pow:13,spd:3.3,reach:84,fx:'#ffc04a',
  look:{skin:'#e8b890',hair:'#e8e8e8',body:'#c77a2c',sub:'#6b3b12',pants:'#5a3a1a',boots:'#3a2410',hat:'huang',hs:'topknot',eye:'#b0802a',beard:'white',weapon:'dao',armor:'plate',cape:'#8a3a12',face:'normal'},
  desc:['백발백중의 노장. 대도와 활을 함께 쓴다.','연속기 마지막 일격에 불화살을 쏜다.','필살기: 하늘을 뒤덮는 폭렬 화살비.'],
  end:'황충은 백발을 쓸어넘기며 웃었다. "늙었다고? 아직 활시위가 팽팽하다네!"'},
 {id:'zhuge',name:'제갈량',zi:'공명',title:'와룡',weapon:'백우선',spName:'팔진뇌격',sp:'thunder',hp:100,pow:11,spd:3.5,reach:80,fx:'#8ad8ff',
  look:{skin:'#f2d0aa',hair:'#1a1a1a',body:'#ece6d4',sub:'#5b4a9e',pants:'#3a2f66',boots:'#2a2a3a',hat:'zhuge',hs:'long',eye:'#6a5ad0',beard:'short',weapon:'fan',armor:'robe',cape:null,face:'calm'},
  desc:['천문과 지리에 통달한 와룡 선생.','연속기 끝에 돌풍을 날려 멀리 있는 적을 친다.','필살기: 팔괘진을 펼쳐 모든 적에게 벼락.'],
  end:'제갈량은 깃털부채를 천천히 부쳤다. "천하삼분은 끝났소. 이제 백성이 쉴 차례요."'},
 {id:'ma',name:'마초',zi:'맹기',title:'금마초',weapon:'호두삽금창',spName:'서량선풍창',sp:'tornado',hp:115,pow:13,spd:3.8,reach:98,fx:'#dfeaff',
  look:{skin:'#f2cfa6',hair:'#2a1a10',body:'#d9dde6',sub:'#c9a227',pants:'#8a8f9a',boots:'#c9a227',hat:'ma',hs:'ponytail',eye:'#d0a020',beard:null,weapon:'spear',armor:'plate',cape:'#f4f4f4',face:'normal',metal:'#f0d870',wood:'#e8e8e8'},
  desc:['서량의 금마초. 사자 투구와 은갑옷의 젊은 맹장.','빠른 발과 긴 창, 균형 잡힌 능력치.','필살기: 적을 빨아들이는 회오리 창격.'],
  end:'마초는 서량의 바람을 향해 창을 들었다. "아버님, 원수를 갚았습니다."'},
 {id:'diao',name:'초선',zi:'—',title:'폐월',weapon:'쌍검',spName:'폐월난무',sp:'charm',hp:95,pow:10,spd:4.3,reach:76,fx:'#ff8ad0',
  look:{skin:'#f8dcc4',hair:'#1a1020',body:'#e86a9a',sub:'#ffd86a',pants:'#b8406a',boots:'#8a2a4a',hat:'diao',hs:'long_f',eye:'#d04a9a',beard:null,weapon:'sword',dual:true,armor:'dress',cape:null,face:'female'},
  desc:['달도 부끄러워 숨는다는 절세미인.','가장 빠른 몸놀림과 쌍검 연속 공격.','필살기: 꽃잎 폭풍 속 검무로 주변을 연속 베기.'],
  end:'초선은 달빛 아래 검을 거두었다. "이제 누구의 계략에도 휘둘리지 않겠어요."'},
 {id:'wei',name:'위연',zi:'문장',title:'반골',weapon:'대도',spName:'반골열화참',sp:'fire',hp:130,pow:15,spd:3.0,reach:94,fx:'#ff7a2a',
  look:{skin:'#c98c5e',hair:'#111111',body:'#6a1e1e',sub:'#2a2a2a',pants:'#2a1414',boots:'#1a1a1a',hat:'wei',hs:'spiky',eye:'#c03030',beard:'short',weapon:'bigdao',armor:'plate',cape:'#3a0a0a',face:'fierce'},
  desc:['뒤통수에 반골이 있다는 사나운 맹장.','대도로 내려찍는 묵직한 공격.','필살기: 대지를 가르며 솟구치는 화염 기둥.'],
  end:'위연은 대도를 땅에 꽂고 크게 웃었다. "누가 감히 나를 죽이랴! ...아무도 없군!"'},
 {id:'lubu',hidden:true,name:'여포',zi:'봉선',title:'천하무쌍',weapon:'방천화극',spName:'무쌍난무',sp:'musou',hp:150,pow:17,spd:3.6,reach:106,fx:'#ff3a3a',
  look:{skin:'#efcfa8',hair:'#1a1010',body:'#7a1a1a',sub:'#e0c040',pants:'#3a0f0f',boots:'#e0c040',hat:'lubu',hs:'long',eye:'#e03a2a',beard:null,weapon:'halberd',armor:'plate',cape:'#b01818',face:'fierce'},
  desc:['[히든] 사람 중의 여포. 모든 능력이 최강.','방천화극의 긴 사거리와 압도적 파괴력.','필살기: 화면을 가르는 무쌍 연속 베기.'],
  end:'여포는 방천화극을 치켜들었다. "천하에 나를 막을 자는 없다! 적토야, 가자!"'},
 {id:'xu',name:'서황',zi:'공명',title:'위의 명장',weapon:'대부(大斧)',spName:'대부개산',sp:'axequake',hp:132,pow:15,spd:3.0,reach:98,fx:'#ffb040',
  look:{skin:'#e8c098',hair:'#1a1410',body:'#3a4a7a',sub:'#c0c8d8',pants:'#222a44',boots:'#1a1a1a',hat:'helm2',hs:'short',eye:'#d09030',beard:'short',weapon:'axe',armor:'plate',cape:'#28305a',face:'fierce',helmc:'#8a90a0'},
  desc:['큰 도끼를 휘두르는 위의 맹장.','묵직한 도끼로 적을 쪼개고 땅을 가른다.','필살기: 대지를 쪼개는 대부의 일격.'],
  end:'서황은 대부를 어깨에 걸쳤다. "주아부의 풍모라 하셨지. 과찬이오."'},
 {id:'gan',name:'감녕',zi:'흥패',title:'금범적',weapon:'쇄편(鎖鞭)',spName:'금범적풍',sp:'whipstorm',hp:112,pow:12,spd:4.0,reach:122,fx:'#ffd84a',
  look:{skin:'#d8a878',hair:'#6a3010',body:'#c89a30',sub:'#2a2a2a',pants:'#3a2a18',boots:'#2a1a10',hat:'gan',hs:'spiky',eye:'#e0a020',beard:null,weapon:'whip',armor:'cloth',cape:'#8a1a1a',face:'fierce'},
  desc:['방울 소리와 함께 나타나는 강동의 수적 출신 맹장.','긴 쇄편으로 멀리 있는 적까지 휘감아 때린다.','필살기: 비단 돛의 폭풍처럼 주변을 휩쓴다.'],
  end:'감녕은 허리의 방울을 흔들었다. "딸랑— 이 소리가 들리면 이미 늦은 거지!"'},
 {id:'sun',name:'손상향',zi:'—',title:'궁요희',weapon:'비궁(飛弓)',spName:'궁요난사',sp:'bowdance',hp:100,pow:11,spd:4.2,reach:80,fx:'#ff6a4a',
  look:{skin:'#f8dcc4',hair:'#b8502a',body:'#d04040',sub:'#f0d060',pants:'#8a2a2a',boots:'#6a2a1a',hat:'sun',hs:'ponytail',eye:'#e06a3a',beard:null,weapon:'bow',armor:'dress',cape:null,face:'female'},
  desc:['활과 무예를 사랑한 강동의 공주.','가볍게 뛰어다니며 화살을 퍼붓는다.','필살기: 공중제비와 함께 화살 폭풍을 쏟아낸다.'],
  end:'손상향은 활을 등에 멨다. "오라버니들, 이제 저도 한몫 했죠?"'}
];

/* 커맨드 전용기 (↓→ + 공격) */
const CMDS={guan:{name:'청룡파',type:'gwave'},zhang:{name:'맹호돌진',type:'charge'},zhao:{name:'창룡섬',type:'flurry'},
  huang:{name:'삼연사',type:'triarrow'},zhuge:{name:'화계',type:'fireball'},ma:{name:'서량돌격',type:'lance'},
  diao:{name:'비화선',type:'petal'},wei:{name:'지열참',type:'quake'},lubu:{name:'방천일섬',type:'redslash'},
  xu:{name:'부월참',type:'axethrow'},gan:{name:'쇄편격',type:'lash'},sun:{name:'연환시',type:'backshot'}};
HEROES.forEach(h=>h.cmd=CMDS[h.id]);
/* 커맨드 표 (도움말·일시정지 화면) */
const CMDLIST=[['↓ → + 공격','무장별 전용기','기력 20'],['↓ ↑ + 공격','승천격 (띄우기)','기력 10'],['→ → (길게)','달리기',''],
  ['달리며 공격','돌진 공격',''],['공격 + 점프 동시','무적 회전베기','체력 6%'],['Shift / O (2P 오른쪽 Shift)','회피 — 방향키로 구르기 · 백스텝','무적'],['필살기 키','초필살기 (컷인)','기력 50'],['1 ~ 4','단축 스킬 (RPG)','내공']];
const BOSS_SHOUT={'안량':'하북의 안량이다!','하후돈':'하후원양이 간다!','하후연':'질풍처럼!','방덕':'관을 메고 왔다!','장각':'황천당립!','여포':'천하무쌍!','허저':'박살내 주마!','장료':'장문원이 여기 있다!','조조':'나를 막을 자는 없다!','사마의':'별은 오늘 밤 진다.','하후은':'청강검을 받아라!'};

const FAC={yellow:{skin:'#e2b98e',hair:'#2a2018',body:'#c9a227',sub:'#6d4c12',pants:'#5a4a2a',boots:'#3a2a18',hat:'scarf',armor:'cloth',face:'normal'},
  dong:{skin:'#e2b98e',hair:'#1a1410',body:'#8a2222',sub:'#3a3a3a',pants:'#3a1a1a',boots:'#1a1a1a',hat:'helm',armor:'cloth',face:'fierce'},
  wei:{skin:'#e2b98e',hair:'#1a1410',body:'#2c4f8f',sub:'#9aa4b8',pants:'#1f2a44',boots:'#1a1a1a',hat:'helm',armor:'cloth',face:'normal'},
  yuan:{skin:'#e2b98e',hair:'#1a1410',body:'#8a6a2a',sub:'#d8c070',pants:'#4a3a1a',boots:'#2a1a10',hat:'helm',helmc:'#7a6030',armor:'cloth',face:'fierce'}};
const ETYPES={s:{hp:32,pow:6,spd:1.7,reach:62,weapon:'sword',exp:10,score:100},
  sp:{hp:38,pow:7,spd:1.5,reach:88,weapon:'spear',exp:12,score:150},
  a:{hp:26,pow:6,spd:1.4,reach:62,weapon:'bow',ranged:true,exp:12,score:150},
  o:{hp:95,pow:10,spd:1.9,reach:78,weapon:'dao',exp:40,score:500,scale:1.15,officer:true},
  /* 역할 병종: 방패병(정면 공격 막음 — 뒤 · 공중 · 강공격으로 파훼) · 기병(예고 후 라인 돌격) · 기수(주변 적 강화, 쓰러지면 사기 붕괴) */
  sh:{hp:52,pow:6,spd:1.3,reach:66,weapon:'sword',exp:16,score:250,shield:true},
  cv:{hp:64,pow:9,spd:2.1,reach:84,weapon:'spear',exp:22,score:350,cavalry:true},
  fl:{hp:46,pow:4,spd:1.25,reach:62,weapon:'flag',exp:20,score:400,banner:true}};
/* 세력별 병종 외형: 군마 색 · 깃발 글자 */
const FAC_EX={yuan:{mount:'#6a4a2a',flagt:'袁',shieldc:'#8a6a2a'},yellow:{mount:'#8a6440',flagt:'黃',shieldc:'#b88a2a'},dong:{mount:'#2e2622',flagt:'董',shieldc:'#7a1c1c'},wei:{mount:'#d8d2c4',flagt:'魏',shieldc:'#2a4a8a'}};
/* 보스 페이즈: 체력 비율(hp) 아래로 내려가면 다음 국면 — seq 순서대로 기술 사용, enter 전환 기믹, line 전환 대사 */
const BOSS_PHASES={
 '장각':[{hp:1,seq:['orb','bolt','orb']},
   {hp:.7,seq:['bolt','orb','bolt'],enter:'barrier',line:'"황천의 결계여, 이 몸을 지켜라!"'},
   {hp:.35,seq:['pray','ult','bolt','orb'],enter:'rage',line:'"태평의 도는 꺼지지 않는다!"'}],
 '여포':[{hp:1,seq:['wave','dash','wave']},
   {hp:.65,seq:['charge3','wave','dash','ult'],enter:'mount',line:'"적토야, 저 버러지들을 짓밟아라!"'},
   {hp:.3,seq:['ult','dash','wave','dash'],enter:'dismount',line:'"이 여봉선을 말에서 끌어내리다니... 재밌구나!"'}],
 '허저':[{hp:1,seq:['slam','grab','slam']},
   {hp:.6,seq:['grab','slam','ult','slam'],enter:'rage',line:'"으아아! 이제 진짜 화났다!"'},
   {hp:.25,seq:['grab','ult','grab','slam'],enter:'rage',line:'"맨손으로 찢어 주마!"'}],
 '장료':[{hp:1,seq:['wave','dash','roar']},
   {hp:.65,seq:['lanes','wave','roar','dash'],enter:'rage',line:'"팔백 기병, 나를 따르라!"'},
   {hp:.3,seq:['lanes','ult','roar','lanes'],enter:'rage',line:'"요래요래! 합비의 악몽을 보여 주마!"'}],
 '조조':[{hp:1,seq:['wave','summon','dash']},
   {hp:.6,seq:['decoy','wave','dash','summon'],enter:'decoy',line:'"어느 것이 진짜 조맹덕인지 맞혀 보아라!"'},
   {hp:.3,seq:['ult','decoy','wave','dash'],enter:'rage',line:'"천하는 결코 너희에게 넘기지 않는다!"'}],
 '하후은':[{hp:1,seq:['dash','counter','wave','counter']}],
 '안량':[{hp:1,seq:['dash','wave','slam']},
   {hp:.6,seq:['charge3','slam','wave','ult'],enter:'mount',line:'"하북 제일의 창칼을 받아라!"'},
   {hp:.25,seq:['ult','slam','dash','slam'],enter:'dismount',line:'"말에서 떨어졌다고 끝난 줄 아느냐!"'}],
 '하후돈':[{hp:1,seq:['dash','wave','summon']},
   {hp:.6,seq:['roar','dash','ult','wave'],enter:'rage',line:'"부모에게 받은 눈이다! 버릴 수 없지!"'},
   {hp:.25,seq:['ult','roar','dash','summon'],enter:'rage',line:'"불길 따위로 이 하후돈을 멈출 수 있을 것 같으냐!"'}],
 '하후연':[{hp:1,seq:['volley','dash','wave']},
   {hp:.6,seq:['lanes','volley','dash','volley'],enter:'rage',line:'"질풍 기병대, 산을 내달려라!"'},
   {hp:.25,seq:['ult','volley','lanes','volley'],enter:'rage',line:'"화살이 다하면 이 몸이 화살이 되리라!"'}],
 '방덕':[{hp:1,seq:['dash','slam','wave']},
   {hp:.6,seq:['charge3','slam','ult','wave'],enter:'mount',line:'"서량의 기마술을 보여 주마!"'},
   {hp:.25,seq:['ult','slam','dash','slam'],enter:'dismount',line:'"관 속에 들어가는 한이 있어도 물러서지 않는다!"'}],
 '사마의':[{hp:1,seq:['orb','bolt','illusion']},
   {hp:.6,seq:['illusion','bolt','summon','orb'],enter:'rage',line:'"공명, 그대의 별은 이미 기울었소."'},
   {hp:.3,seq:['ult','illusion','bolt','illusion'],enter:'rage',line:'"낭고(狼顧)의 눈에서 벗어날 수는 없다!"'}]};

const MIDBOSS={name:'하후은',title:'청강검의 주인',hp:280,pow:12,spd:2.7,reach:72,skills:['dash','wave'],poise:60,score:3000,
  look:{skin:'#efcfa8',hair:'#1a1410',body:'#3a5fa0',sub:'#d8d8e8',pants:'#223344',boots:'#111111',hat:'helm2',weapon:'sword',armor:'plate',cape:'#2a3a6a',scale:1.1,face:'normal',metal:'#a8e0ff'},
  line:'"승상께서 하사하신 청강검의 날을 맛보아라!"'};
const STAGES=[
 {title:'제1장  탁현',sub:'황건적의 난',bg:'plains',fac:'yellow',len:3200,
  story:['중평 원년(184년), 한 황실의 기강은 무너지고 천하는 굶주렸다.',
   '"창천이사 황천당립(蒼天已死 黃天當立)!"',
   '태평도의 교주 장각이 이끄는 황건적 수십만이 들불처럼 일어났다.',
   '탁현의 복숭아 동산에서 의형제를 맺은 영웅들이 의용군을 일으킨다.',
   '— 마을 노인이 말하길, 장각은 항아리마다 비서(秘書)를 나눠 숨겼다던데...'],
  waves:[[450,'s s s'],[1000,'s sh sp a'],[1650,'sp s a fl s'],[2300,'o sh sp a']],
  jars:[350,650,980,1400,1900,2450],countJars:true,
  boss:{name:'장각',title:'천공장군',hp:430,pow:10,spd:2.0,reach:84,skills:['bolt','orb'],escort:'s s a',score:8000,
   look:{skin:'#e6c39a',hair:'#dddddd',body:'#d8b52a',sub:'#7a1a10',pants:'#6a5010',boots:'#3a2a10',hat:'taoist',beard:'white',weapon:'staff',armor:'robe',cape:'#e8c020',face:'fierce'},
   line:'"황천당립! 하늘의 뜻을 거스르는 자, 벼락을 맞으리라!"'}},
 {title:'제2장  호뢰관',sub:'천하무쌍 여봉선',bg:'fortress',fac:'dong',len:3400,
  story:['십팔로 제후가 모여 반동탁 연합군을 결성했다.',
   '폭군 동탁은 낙양을 불태우고 장안으로 천도하려 한다.',
   '호뢰관을 지키는 자는 천하무쌍 — 여포 봉선.',
   '"사람 중엔 여포, 말 중엔 적토(人中呂布 馬中赤兎)"라 했던가.',
   '— 불타는 낙양 궁터의 우물 속에서 오색 빛이 새어 나온다는 소문이 있다...'],
  waves:[[450,'s sp sh sp'],[1050,'a cv s fl o'],[1700,'sp sh cv a s'],[2400,'o o cv a fl']],
  jars:[800,1450,2650],well:1900,
  boss:{name:'여포',title:'천하무쌍',hp:720,pow:16,spd:2.6,reach:104,skills:['dash','dash','wave'],escort:'s sp',score:12000,poise:110,
   look:Object.assign({},HEROES[8].look,{scale:1.15}),line:'"하찮은 것들이 몇이 오든 이 방천화극 앞에선 매한가지!"'}},
 {title:'제5장  장판파',sub:'단기구주',bg:'bridge',fac:'wei',len:3600,
  story:['박망파의 불길로 하후돈을 물리쳤으나, 조조는 몸소 오십만 대군을 이끌고 남하했다.',
   '형주를 잃은 유비는 백성 십만을 이끌고 남으로 피난한다.',
   '조조의 정예 호표기가 장판파로 들이닥쳤다.',
   '"연인 장익덕이 여기 있다! 누가 감히 나와 사생을 결하겠느냐!"',
   '— 조조의 총애를 받는 하후은이 보검 청강검을 차고 있다 한다.',
   '— 재빨리 쓰러뜨린다면, 그 검을 빼앗을 수 있을지도...'],
  waves:[[450,'s cv sp a'],[1100,'H s s'],[1800,'cv sp a fl o'],[2600,'o sh cv cv a']],
  jars:[700,1500,2900],
  boss:{name:'허저',title:'호치(虎痴)',hp:880,pow:18,spd:1.9,reach:84,skills:['slam','slam','dash'],escort:'s s',score:14000,poise:140,
   look:{skin:'#c98c5a',hair:'#111111',body:'#6a4a2a',sub:'#2a2a2a',pants:'#3a2a1a',boots:'#1a1a1a',hat:'none',beard:'spiky',weapon:'mace',armor:'bare',scale:1.3,face:'fierce'},
   line:'"호치 허중강이 네놈 머리통을 박살내 주마!"'}},
 {title:'제6장  적벽',sub:'동남풍이 분다',bg:'redcliff',fac:'wei',len:3600,
  story:['장판파를 벗어난 유비는 강동의 손권과 손을 잡았다.',
   '조조의 팔십만 대군이 장강에 배를 띄웠다.',
   '방통의 연환계로 전선들은 쇠사슬로 묶였고,',
   '칠성단에서 올린 기도에 한겨울의 동남풍이 불어온다.',
   '황개의 화선이 불을 뿜는다 — 지금이다, 적의 기함으로 돌격하라!'],
  waves:[[450,'s sh a a'],[1100,'sp sh o fl'],[1800,'a a a sh s'],[2600,'o o sp fl cv']],
  jars:[900,1700,2500],
  boss:{name:'장료',title:'위의 오자양장',hp:880,pow:17,spd:2.8,reach:100,skills:['dash','wave','dash'],escort:'sp a',score:15000,poise:120,
   look:{skin:'#eecba4',hair:'#1a1410',body:'#26457f',sub:'#c0c8d8',pants:'#18284a',boots:'#1a1a1a',hat:'helm2',beard:'short',weapon:'halberd',armor:'plate',cape:'#1a2a5a',scale:1.12,face:'fierce'},
   line:'"장문원이 여기 있다! 불길 따위에 물러서지 마라!"'}},
 {title:'제7장  화용도',sub:'난세의 간웅',bg:'pass',fac:'wei',len:3800,
  story:['적벽의 불길은 사흘 밤낮을 탔다.',
   '대패한 조조는 좁은 화용도로 달아난다.',
   '비가 쏟아지는 진흙길, 지친 패잔병들의 발소리.',
   '"하하하! 제갈량도 여기에 복병을 둘 생각은 못 했겠지!"',
   '난세의 간웅 조맹덕 — 여기서 결판을 내자!',
   '— 쓰러진 조조를 놓아줄 것인가, 사로잡을 것인가. 그 선택이 훗날을 바꾼다.'],
  waves:[[450,'s sp sh a'],[1100,'o cv s fl a'],[1850,'sh sh a a o'],[2700,'o cv cv fl a a']],
  jars:[750,1600,2450,3200],
  boss:{name:'조조',title:'난세의 간웅',hp:1000,pow:16,spd:2.3,reach:80,skills:['summon','wave','dash','wave'],escort:'o a',score:20000,poise:120,
   look:{skin:'#efcfa8',hair:'#1a1410',body:'#223a7a',sub:'#d8b040',pants:'#141f44',boots:'#1a1a1a',hat:'crown',beard:'short',weapon:'sword',armor:'robe',cape:'#6a1010',scale:1.1,face:'calm',metal:'#c8f0ff'},
   line:'"내가 천하를 버릴지언정, 천하가 나를 버리게 하진 않으리라!"'}},
 {title:'비장(秘章)  오장원',sub:'별이 지는 밤',bg:'night',fac:'wei',len:3000,hidden:true,
  story:['세 보물이 공명하며 한 줄기 별빛이 되어 하늘로 솟았다.',
   '태평요술서 · 전국옥새 · 청강검 — 하늘이 한 황실에 다시 기회를 준 것이다.',
   '그러나 오장원의 밤, 수명을 잇는 칠성등의 불꽃이 흔들린다.',
   '모든 것을 꿰뚫어 본 사마의가 칠성등을 끄기 위해 진을 쳤다!',
   '— 운명의 별을 지켜라 —'],
  waves:[[450,'o sh s a fl'],[1100,'o cv sp cv'],[1900,'o o a a sh fl']],
  jars:[800,1600,2300],
  boss:{name:'사마의',title:'낭고(狼顧)의 군사',hp:1300,pow:18,spd:2.3,reach:82,skills:['bolt','orb','summon','bolt'],escort:'o',score:30000,poise:120,
   look:{skin:'#e6c9a8',hair:'#1a1a1a',body:'#2a2a4a',sub:'#8a2a8a',pants:'#15152a',boots:'#111111',hat:'taoist',beard:'long',weapon:'fan',armor:'robe',cape:'#3a1a5a',scale:1.1,face:'calm'},
   line:'"별의 운명은 이미 정해졌다. 칠성등은 오늘 밤 꺼진다."'}},
 /* ---- 추가 장 (진행 순서: 탁현 → 호뢰관 → 백마 → 박망파 → 장판파 → 적벽 → 화용도 → 정군산 → 번성 → [비장]) ---- */
 {title:'제3장  백마',sub:'관우, 안량을 베다',bg:'plains',fac:'yuan',len:3400,mus:1,
  story:['건안 5년(200년), 하북의 패자 원소가 십만 대군을 일으켰다.',
   '선봉장 안량이 백마성을 에워싸고, 조조는 서둘러 구원에 나선다.',
   '"하북의 안량과 문추 — 천하에 그 둘을 당할 자 없다."',
   '하비성에서 흩어진 도원의 형제들은 아직 서로의 생사를 모른다.',
   '— 안량의 목을 베는 자가 이 전장의 주인이 되리라.'],
  waves:[[450,'s sp s a'],[1050,'cv s sh a'],[1700,'sp sp fl a o'],[2400,'o cv cv sh a']],
  jars:[700,1500,2600],
  boss:{name:'안량',title:'하북의 명장',hp:820,pow:16,spd:2.5,reach:100,skills:['dash','wave','slam'],escort:'cv s',score:13000,poise:120,
   look:{skin:'#d8a878',hair:'#1a1410',body:'#6a4a1a',sub:'#e0c050',pants:'#3a2a10',boots:'#1a1a1a',hat:'helm2',helmc:'#a08030',beard:'spiky',weapon:'bigdao',armor:'plate',cape:'#5a2a10',scale:1.18,face:'fierce',eye:'#8a4a10'},
   line:'"하북의 안량이다! 목을 내놓고 가라!"'}},
 {title:'제4장  박망파',sub:'와룡의 첫 불길',bg:'plains',tint:'rgba(255,110,40,.16)',fac:'wei',len:3400,mus:3,
  story:['삼고초려 끝에 와룡 제갈량이 유비의 군사가 되었다.',
   '"물고기가 물을 얻었다" — 그러나 관우와 장비는 아직 젊은 서생을 믿지 못한다.',
   '그때 하후돈이 십만 군을 이끌고 신야로 쳐들어왔다.',
   '공명의 명은 단 하나 — "박망파 좁은 길로 적을 끌어들이시오. 신호가 오르면 불을 놓으리다."',
   '— 불길이 오르면, 불똥은 적과 아군을 가리지 않는다.'],
  waves:[[450,'s s sp a'],[1050,'sh sp fl a'],[1700,'cv s s o a'],[2400,'o sh cv fl a']],
  jars:[800,1600,2500],
  boss:{name:'하후돈',title:'외눈의 맹장',hp:900,pow:16,spd:2.6,reach:96,skills:['dash','wave','summon'],escort:'s sp a',score:14000,poise:125,roarLine:'"비켜라! 하후원양이 간다!"',
   look:{skin:'#e8c098',hair:'#1a1410',body:'#2c3f7f',sub:'#c0c8d8',pants:'#18284a',boots:'#1a1a1a',hat:'helm2',helmc:'#707888',beard:'short',weapon:'spear',armor:'plate',cape:'#1a2a5a',scale:1.14,face:'fierce',patch:true,eye:'#6a3a1a'},
   line:'"서생 하나의 잔꾀 따위, 이 하후돈이 짓밟아 주마!"'}},
 {title:'제8장  정군산',sub:'노장의 화살',bg:'pass',rain:false,tint:'rgba(255,200,120,.08)',fac:'wei',len:3600,mus:4,
  story:['적벽 이후 십 년, 유비는 익주를 얻고 한중을 노린다.',
   '한중의 관문 정군산 — 위의 명장 하후연이 산마루에 진을 쳤다.',
   '"질풍" 하후연의 궁기병은 사흘 걸음을 하루에 달린다.',
   '법정이 산꼭대기에서 깃발을 흔드는 순간이 총공격의 신호다.',
   '— 산비탈에는 하후연의 궁수들이 화살비를 퍼붓는다.'],
  waves:[[450,'a a s sp'],[1100,'cv cv sh a'],[1800,'a a fl o sh'],[2600,'o cv cv a a fl']],
  jars:[750,1650,2700],
  boss:{name:'하후연',title:'질풍의 장수',hp:950,pow:17,spd:2.9,reach:92,skills:['volley','dash','wave'],escort:'a a cv',score:17000,poise:120,
   look:{skin:'#eecba4',hair:'#1a1410',body:'#2a4a6a',sub:'#c0c8d8',pants:'#18284a',boots:'#1a1a1a',hat:'helm2',helmc:'#8a9098',beard:'short',weapon:'bow',armor:'plate',cape:'#203a5a',scale:1.12,face:'fierce',eye:'#3a4a7a'},
   line:'"산 위에서 쏘는 화살은 피할 곳이 없다!"'}},
 {title:'제9장  번성',sub:'칠군을 수몰시키다',bg:'fortress',rain:true,tint:'rgba(20,50,110,.22)',fac:'wei',len:3600,mus:2,
  story:['건안 24년(219년) 가을, 관우가 형주에서 북진해 번성을 에워쌌다.',
   '조조는 우금에게 칠군을 주어 구원하게 하고, 방덕을 선봉으로 삼았다.',
   '방덕은 관을 짊어지고 출진했다 — "관우를 베지 못하면 내가 이 관에 들어가리라."',
   '가을 장마가 한수를 불리고 있다. 둑이 터지는 날이 승부의 날이다.',
   '— 물길이 열리면 적진 전체가 물에 잠기리라.'],
  waves:[[450,'s sh sp a'],[1100,'o sh fl a'],[1800,'cv cv sp a a'],[2600,'o o sh fl cv']],
  jars:[800,1700,2750],
  boss:{name:'방덕',title:'관을 멘 장수',hp:1080,pow:18,spd:2.5,reach:100,skills:['dash','slam','wave'],escort:'o sh',score:22000,poise:135,
   look:{skin:'#d8a878',hair:'#1a1410',body:'#4a4a58',sub:'#c8c8d0',pants:'#2a2a34',boots:'#1a1a1a',hat:'helm',helmc:'#50505e',beard:'spiky',weapon:'bigdao',armor:'plate',cape:'#1a1a22',scale:1.16,face:'fierce'},
   line:'"관을 메고 왔다! 오늘 이 관에 들어갈 자는 누구냐!"'}}
];
/* use:true = 인벤토리에 보관했다가 아이템 키로 사용 (n = 한 번에 얻는 개수) */
const ITEMS={bun:{name:'고기만두',msg:'체력 +30'},chicken:{name:'통닭',msg:'체력 +70'},
  gold:{name:'금괴',msg:'+1000'},silver:{name:'은괴',msg:'+500'},gem:{name:'야명주',msg:'+3000'},
  knife:{name:'비도',use:true,n:5,max:30,desc:'앞으로 던지는 단검'},
  wine:{name:'술',use:true,n:1,max:9,desc:'기력 +50'},
  bomb:{name:'화약통',use:true,n:2,max:9,desc:'던지면 폭발하는 화약'},
  elixir:{name:'선단',use:true,n:1,max:5,desc:'체력 60% 회복'},
  tactic:{name:'병법서',use:true,n:1,max:5,desc:'10초간 공격력 1.5배'},
  haste:{name:'신행부',use:true,n:1,max:5,desc:'10초간 이동속도 1.5배'},
  shield:{name:'금강부',use:true,n:1,max:5,desc:'8초간 받는 피해 70% 감소'},
  tcharm:{name:'뇌부',use:true,n:1,max:5,desc:'화면의 모든 적에게 벼락'},
  book:{name:'태평요술서',hz:'太平要術書',treasure:true,msg:'장각이 숨긴 천서. 기력이 가득 차고 필살기 위력 상승'},
  seal:{name:'전국옥새',hz:'傳國玉璽',treasure:true,msg:'천명을 받은 자의 증표. 받는 피해 20% 감소'},
  sword:{name:'청강검',hz:'靑釭劍',treasure:true,msg:'조조의 보검. 공격력 +4'},
  horse:{name:'적토마',hz:'赤兎馬',treasure:true,msg:'하루에 천 리를 달리는 명마. 이동속도 상승'},
  /* RPG: 장비 · 금화 · 재료 (필드 드랍) */
  gear:{name:'장비'},coin:{name:'금화'},mat:{name:'재료'}};
